# Site settings
title: Jianfeng Zhang blog
email: jf.zhang958@outlook.com
description: "Musings of a Computer Scientist."
baseurl: ""
url: "https://jfzhang95.github.io"
blogurl: "http://jfzhang95.github.io/blog"
#twitter_username: karpathy
github_username:  jfzhang95

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
